/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Audit Logs Web API
 * OpenAPI Spec for Kibo Audit Logs Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const basePathTemplate = 'https://{tenantPodHost}/api'
