/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Content Service
 * OpenAPI Spec for Kibo Content Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HttpVersionPolicy = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type HttpVersionPolicy = typeof HttpVersionPolicy[keyof typeof HttpVersionPolicy];


export function HttpVersionPolicyFromJSON(json: any): HttpVersionPolicy {
    return HttpVersionPolicyFromJSONTyped(json, false);
}

export function HttpVersionPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpVersionPolicy {
    return json as HttpVersionPolicy;
}

export function HttpVersionPolicyToJSON(value?: HttpVersionPolicy | null): any {
    return value as any;
}

