/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Content Service
 * OpenAPI Spec for Kibo Content Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';

/**
 * 
 * @export
 * @interface PropertyTypeCollection
 */
export interface PropertyTypeCollection {
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeCollection
     */
    startIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeCollection
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeCollection
     */
    pageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyTypeCollection
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<PropertyType>}
     * @memberof PropertyTypeCollection
     */
    items?: Array<PropertyType> | null;
}

/**
 * Check if a given object implements the PropertyTypeCollection interface.
 */
export function instanceOfPropertyTypeCollection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyTypeCollectionFromJSON(json: any): PropertyTypeCollection {
    return PropertyTypeCollectionFromJSONTyped(json, false);
}

export function PropertyTypeCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyTypeCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startIndex': !exists(json, 'startIndex') ? undefined : json['startIndex'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageCount': !exists(json, 'pageCount') ? undefined : json['pageCount'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(PropertyTypeFromJSON)),
    };
}

export function PropertyTypeCollectionToJSON(value?: PropertyTypeCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startIndex': value.startIndex,
        'pageSize': value.pageSize,
        'pageCount': value.pageCount,
        'totalCount': value.totalCount,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(PropertyTypeToJSON)),
    };
}

