/* tslint:disable */
/* eslint-disable */
/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request/Response object for a tag
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * Tag ID
     * @type {number}
     * @memberof Tag
     */
    tagID?: number;
    /**
     * Tag Value
     * @type {string}
     * @memberof Tag
     */
    tagValue?: string;
    /**
     * Whether or not this tag is the default tag for its category.
     * @type {boolean}
     * @memberof Tag
     */
    isDefault?: boolean;
    /**
     * Percentage of available inventory this tag will get when the percentage update is performed. Must be between 0 and 100 (inclusive).
     * @type {number}
     * @memberof Tag
     */
    percent?: number;
    /**
     * Date this tag was created
     * @type {string}
     * @memberof Tag
     */
    created?: string;
    /**
     * Date this tag was last updated
     * @type {string}
     * @memberof Tag
     */
    updated?: string;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tagID': !exists(json, 'tagID') ? undefined : json['tagID'],
        'tagValue': !exists(json, 'tagValue') ? undefined : json['tagValue'],
        'isDefault': !exists(json, 'isDefault') ? undefined : json['isDefault'],
        'percent': !exists(json, 'percent') ? undefined : json['percent'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
    };
}

export function TagToJSON(value?: Tag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tagID': value.tagID,
        'tagValue': value.tagValue,
        'isDefault': value.isDefault,
        'percent': value.percent,
        'created': value.created,
        'updated': value.updated,
    };
}

