/* tslint:disable */
/* eslint-disable */
/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExportSettingsS3 } from './ExportSettingsS3';
import {
    ExportSettingsS3FromJSON,
    ExportSettingsS3FromJSONTyped,
    ExportSettingsS3ToJSON,
} from './ExportSettingsS3';

/**
 * Request needed updating existing Export Settings S3
 * @export
 * @interface UpdateExportSettingsS3Request
 */
export interface UpdateExportSettingsS3Request {
    /**
     * Export Settings Name to associate the ftp settings with
     * @type {string}
     * @memberof UpdateExportSettingsS3Request
     */
    exportSettingsName: string;
    /**
     * 
     * @type {ExportSettingsS3}
     * @memberof UpdateExportSettingsS3Request
     */
    exportSettingsS3: ExportSettingsS3;
    /**
     * Location Code
     * @type {string}
     * @memberof UpdateExportSettingsS3Request
     */
    locationCode?: string;
    /**
     * user id
     * @type {number}
     * @memberof UpdateExportSettingsS3Request
     */
    userID?: number;
    /**
     * how many results to show per page
     * @type {number}
     * @memberof UpdateExportSettingsS3Request
     */
    pageSize?: number;
    /**
     * which page to show
     * @type {number}
     * @memberof UpdateExportSettingsS3Request
     */
    pageNum?: number;
    /**
     * index to sort results by
     * @type {string}
     * @memberof UpdateExportSettingsS3Request
     */
    sortBy?: string;
}

/**
 * Check if a given object implements the UpdateExportSettingsS3Request interface.
 */
export function instanceOfUpdateExportSettingsS3Request(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exportSettingsName" in value;
    isInstance = isInstance && "exportSettingsS3" in value;

    return isInstance;
}

export function UpdateExportSettingsS3RequestFromJSON(json: any): UpdateExportSettingsS3Request {
    return UpdateExportSettingsS3RequestFromJSONTyped(json, false);
}

export function UpdateExportSettingsS3RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateExportSettingsS3Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exportSettingsName': json['exportSettingsName'],
        'exportSettingsS3': ExportSettingsS3FromJSON(json['exportSettingsS3']),
        'locationCode': !exists(json, 'locationCode') ? undefined : json['locationCode'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageNum': !exists(json, 'pageNum') ? undefined : json['pageNum'],
        'sortBy': !exists(json, 'sortBy') ? undefined : json['sortBy'],
    };
}

export function UpdateExportSettingsS3RequestToJSON(value?: UpdateExportSettingsS3Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exportSettingsName': value.exportSettingsName,
        'exportSettingsS3': ExportSettingsS3ToJSON(value.exportSettingsS3),
        'locationCode': value.locationCode,
        'userID': value.userID,
        'pageSize': value.pageSize,
        'pageNum': value.pageNum,
        'sortBy': value.sortBy,
    };
}

