/* tslint:disable */
/* eslint-disable */
/**
 * Kibo AppDev Service
 * OpenAPI Spec for Kibo AppDev Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes an event that a 3rd party developer can subscribe to.
 * @export
 * @interface AppDevEvent
 */
export interface AppDevEvent {
    /**
     * Unique identifier of an Event record.
     * @type {number}
     * @memberof AppDevEvent
     */
    eventId?: number;
    /**
     * The name of the event.
     * @type {string}
     * @memberof AppDevEvent
     */
    eventName?: string | null;
    /**
     * The category the event belongs to.
     * @type {string}
     * @memberof AppDevEvent
     */
    eventCategory?: string | null;
    /**
     * The Api Version Number which defines what events are available for a given API version.
     * @type {string}
     * @memberof AppDevEvent
     */
    apiVersionNumber?: string | null;
}

/**
 * Check if a given object implements the AppDevEvent interface.
 */
export function instanceOfAppDevEvent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppDevEventFromJSON(json: any): AppDevEvent {
    return AppDevEventFromJSONTyped(json, false);
}

export function AppDevEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppDevEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': !exists(json, 'eventId') ? undefined : json['eventId'],
        'eventName': !exists(json, 'eventName') ? undefined : json['eventName'],
        'eventCategory': !exists(json, 'eventCategory') ? undefined : json['eventCategory'],
        'apiVersionNumber': !exists(json, 'apiVersionNumber') ? undefined : json['apiVersionNumber'],
    };
}

export function AppDevEventToJSON(value?: AppDevEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventId': value.eventId,
        'eventName': value.eventName,
        'eventCategory': value.eventCategory,
        'apiVersionNumber': value.apiVersionNumber,
    };
}

