/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoostValue
 */
export interface BoostValue {
    /**
     * 
     * @type {string}
     * @memberof BoostValue
     */
    value?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BoostValue
     */
    boost?: number;
    /**
     * 
     * @type {string}
     * @memberof BoostValue
     */
    operator?: string | null;
}

/**
 * Check if a given object implements the BoostValue interface.
 */
export function instanceOfBoostValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BoostValueFromJSON(json: any): BoostValue {
    return BoostValueFromJSONTyped(json, false);
}

export function BoostValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoostValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'boost': !exists(json, 'boost') ? undefined : json['boost'],
        'operator': !exists(json, 'operator') ? undefined : json['operator'],
    };
}

export function BoostValueToJSON(value?: BoostValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'boost': value.boost,
        'operator': value.operator,
    };
}

