/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensibleAttributeValidation
 */
export interface ExtensibleAttributeValidation {
    /**
     * 
     * @type {string}
     * @memberof ExtensibleAttributeValidation
     */
    regularExpression?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExtensibleAttributeValidation
     */
    minStringLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExtensibleAttributeValidation
     */
    maxStringLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExtensibleAttributeValidation
     */
    minNumericValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExtensibleAttributeValidation
     */
    maxNumericValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ExtensibleAttributeValidation
     */
    minDateTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExtensibleAttributeValidation
     */
    maxDateTime?: Date | null;
}

/**
 * Check if a given object implements the ExtensibleAttributeValidation interface.
 */
export function instanceOfExtensibleAttributeValidation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExtensibleAttributeValidationFromJSON(json: any): ExtensibleAttributeValidation {
    return ExtensibleAttributeValidationFromJSONTyped(json, false);
}

export function ExtensibleAttributeValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensibleAttributeValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regularExpression': !exists(json, 'regularExpression') ? undefined : json['regularExpression'],
        'minStringLength': !exists(json, 'minStringLength') ? undefined : json['minStringLength'],
        'maxStringLength': !exists(json, 'maxStringLength') ? undefined : json['maxStringLength'],
        'minNumericValue': !exists(json, 'minNumericValue') ? undefined : json['minNumericValue'],
        'maxNumericValue': !exists(json, 'maxNumericValue') ? undefined : json['maxNumericValue'],
        'minDateTime': !exists(json, 'minDateTime') ? undefined : (json['minDateTime'] === null ? null : new Date(json['minDateTime'])),
        'maxDateTime': !exists(json, 'maxDateTime') ? undefined : (json['maxDateTime'] === null ? null : new Date(json['maxDateTime'])),
    };
}

export function ExtensibleAttributeValidationToJSON(value?: ExtensibleAttributeValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regularExpression': value.regularExpression,
        'minStringLength': value.minStringLength,
        'maxStringLength': value.maxStringLength,
        'minNumericValue': value.minNumericValue,
        'maxNumericValue': value.maxNumericValue,
        'minDateTime': value.minDateTime === undefined ? undefined : (value.minDateTime === null ? null : value.minDateTime.toISOString()),
        'maxDateTime': value.maxDateTime === undefined ? undefined : (value.maxDateTime === null ? null : value.maxDateTime.toISOString()),
    };
}

