/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductVariation } from './ProductVariation';
import {
    ProductVariationFromJSON,
    ProductVariationFromJSONTyped,
    ProductVariationToJSON,
} from './ProductVariation';

/**
 * Collection of product variations where the variations are returned in a series of pages.
 * @export
 * @interface ProductVariationPagedCollection
 */
export interface ProductVariationPagedCollection {
    /**
     * 
     * @type {number}
     * @memberof ProductVariationPagedCollection
     */
    startIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariationPagedCollection
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariationPagedCollection
     */
    pageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariationPagedCollection
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ProductVariation>}
     * @memberof ProductVariationPagedCollection
     */
    items?: Array<ProductVariation> | null;
}

/**
 * Check if a given object implements the ProductVariationPagedCollection interface.
 */
export function instanceOfProductVariationPagedCollection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductVariationPagedCollectionFromJSON(json: any): ProductVariationPagedCollection {
    return ProductVariationPagedCollectionFromJSONTyped(json, false);
}

export function ProductVariationPagedCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariationPagedCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startIndex': !exists(json, 'startIndex') ? undefined : json['startIndex'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageCount': !exists(json, 'pageCount') ? undefined : json['pageCount'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(ProductVariationFromJSON)),
    };
}

export function ProductVariationPagedCollectionToJSON(value?: ProductVariationPagedCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startIndex': value.startIndex,
        'pageSize': value.pageSize,
        'pageCount': value.pageCount,
        'totalCount': value.totalCount,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(ProductVariationToJSON)),
    };
}

