/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuditInfo } from './AuditInfo';
import {
    AuditInfoFromJSON,
    AuditInfoFromJSONTyped,
    AuditInfoToJSON,
} from './AuditInfo';
import type { ListingSettings } from './ListingSettings';
import {
    ListingSettingsFromJSON,
    ListingSettingsFromJSONTyped,
    ListingSettingsToJSON,
} from './ListingSettings';
import type { ProductSuggestSettings } from './ProductSuggestSettings';
import {
    ProductSuggestSettingsFromJSON,
    ProductSuggestSettingsFromJSONTyped,
    ProductSuggestSettingsToJSON,
} from './ProductSuggestSettings';
import type { SiteSearchSettings } from './SiteSearchSettings';
import {
    SiteSearchSettingsFromJSON,
    SiteSearchSettingsFromJSONTyped,
    SiteSearchSettingsToJSON,
} from './SiteSearchSettings';
import type { SuggestSettings } from './SuggestSettings';
import {
    SuggestSettingsFromJSON,
    SuggestSettingsFromJSONTyped,
    SuggestSettingsToJSON,
} from './SuggestSettings';

/**
 * Settings to control product search and indexing behavior
 * @export
 * @interface SearchSettings
 */
export interface SearchSettings {
    /**
     * 
     * @type {string}
     * @memberof SearchSettings
     */
    settingsName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchSettings
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchSettings
     */
    isDefault?: boolean;
    /**
     * 
     * @type {SiteSearchSettings}
     * @memberof SearchSettings
     */
    siteSearchSettings?: SiteSearchSettings;
    /**
     * 
     * @type {ProductSuggestSettings}
     * @memberof SearchSettings
     */
    productSuggestSettings?: ProductSuggestSettings;
    /**
     * 
     * @type {SuggestSettings}
     * @memberof SearchSettings
     */
    categorySuggestSettings?: SuggestSettings;
    /**
     * 
     * @type {ListingSettings}
     * @memberof SearchSettings
     */
    listingSettings?: ListingSettings;
    /**
     * 
     * @type {AuditInfo}
     * @memberof SearchSettings
     */
    auditInfo?: AuditInfo;
}

/**
 * Check if a given object implements the SearchSettings interface.
 */
export function instanceOfSearchSettings(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchSettingsFromJSON(json: any): SearchSettings {
    return SearchSettingsFromJSONTyped(json, false);
}

export function SearchSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'settingsName': !exists(json, 'settingsName') ? undefined : json['settingsName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isDefault': !exists(json, 'isDefault') ? undefined : json['isDefault'],
        'siteSearchSettings': !exists(json, 'siteSearchSettings') ? undefined : SiteSearchSettingsFromJSON(json['siteSearchSettings']),
        'productSuggestSettings': !exists(json, 'productSuggestSettings') ? undefined : ProductSuggestSettingsFromJSON(json['productSuggestSettings']),
        'categorySuggestSettings': !exists(json, 'categorySuggestSettings') ? undefined : SuggestSettingsFromJSON(json['categorySuggestSettings']),
        'listingSettings': !exists(json, 'listingSettings') ? undefined : ListingSettingsFromJSON(json['listingSettings']),
        'auditInfo': !exists(json, 'auditInfo') ? undefined : AuditInfoFromJSON(json['auditInfo']),
    };
}

export function SearchSettingsToJSON(value?: SearchSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'settingsName': value.settingsName,
        'description': value.description,
        'isDefault': value.isDefault,
        'siteSearchSettings': SiteSearchSettingsToJSON(value.siteSearchSettings),
        'productSuggestSettings': ProductSuggestSettingsToJSON(value.productSuggestSettings),
        'categorySuggestSettings': SuggestSettingsToJSON(value.categorySuggestSettings),
        'listingSettings': ListingSettingsToJSON(value.listingSettings),
        'auditInfo': AuditInfoToJSON(value.auditInfo),
    };
}

