/* tslint:disable */
/* eslint-disable */
/**
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuditInfo } from './AuditInfo';
import {
    AuditInfoFromJSON,
    AuditInfoFromJSONTyped,
    AuditInfoToJSON,
} from './AuditInfo';

/**
 * Used to group channels together to manage common channel information.
 * @export
 * @interface ChannelGroup
 */
export interface ChannelGroup {
    /**
     * Tenant that owns the channel.
     * @type {number}
     * @memberof ChannelGroup
     */
    tenantId?: number;
    /**
     * Code to uniquely identify the channel.
     * @type {string}
     * @memberof ChannelGroup
     */
    code?: string | null;
    /**
     * Friendly name of the channel.
     * @type {string}
     * @memberof ChannelGroup
     */
    name?: string | null;
    /**
     * 
     * @type {AuditInfo}
     * @memberof ChannelGroup
     */
    auditInfo?: AuditInfo;
}

/**
 * Check if a given object implements the ChannelGroup interface.
 */
export function instanceOfChannelGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelGroupFromJSON(json: any): ChannelGroup {
    return ChannelGroupFromJSONTyped(json, false);
}

export function ChannelGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tenantId': !exists(json, 'tenantId') ? undefined : json['tenantId'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'auditInfo': !exists(json, 'auditInfo') ? undefined : AuditInfoFromJSON(json['auditInfo']),
    };
}

export function ChannelGroupToJSON(value?: ChannelGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tenantId': value.tenantId,
        'code': value.code,
        'name': value.name,
        'auditInfo': AuditInfoToJSON(value.auditInfo),
    };
}

