/* tslint:disable */
/* eslint-disable */
/**
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShippingRate } from './ShippingRate';
import {
    ShippingRateFromJSON,
    ShippingRateFromJSONTyped,
    ShippingRateToJSON,
} from './ShippingRate';

/**
 * 
 * @export
 * @interface CheckoutGroupShippingMethod
 */
export interface CheckoutGroupShippingMethod {
    /**
     * 
     * @type {string}
     * @memberof CheckoutGroupShippingMethod
     */
    groupingId?: string | null;
    /**
     * 
     * @type {ShippingRate}
     * @memberof CheckoutGroupShippingMethod
     */
    shippingRate?: ShippingRate;
}

/**
 * Check if a given object implements the CheckoutGroupShippingMethod interface.
 */
export function instanceOfCheckoutGroupShippingMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckoutGroupShippingMethodFromJSON(json: any): CheckoutGroupShippingMethod {
    return CheckoutGroupShippingMethodFromJSONTyped(json, false);
}

export function CheckoutGroupShippingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutGroupShippingMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupingId': !exists(json, 'groupingId') ? undefined : json['groupingId'],
        'shippingRate': !exists(json, 'shippingRate') ? undefined : ShippingRateFromJSON(json['shippingRate']),
    };
}

export function CheckoutGroupShippingMethodToJSON(value?: CheckoutGroupShippingMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupingId': value.groupingId,
        'shippingRate': ShippingRateToJSON(value.shippingRate),
    };
}

