/* tslint:disable */
/* eslint-disable */
/**
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PricingDiscount } from './PricingDiscount';
import {
    PricingDiscountFromJSON,
    PricingDiscountFromJSONTyped,
    PricingDiscountToJSON,
} from './PricingDiscount';

/**
 * 
 * @export
 * @interface PricingAppliedLineItemProductDiscount
 */
export interface PricingAppliedLineItemProductDiscount {
    /**
     * 
     * @type {boolean}
     * @memberof PricingAppliedLineItemProductDiscount
     */
    appliesToSalePrice?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PricingAppliedLineItemProductDiscount
     */
    impact?: number;
    /**
     * 
     * @type {PricingDiscount}
     * @memberof PricingAppliedLineItemProductDiscount
     */
    discount?: PricingDiscount;
    /**
     * 
     * @type {string}
     * @memberof PricingAppliedLineItemProductDiscount
     */
    couponCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PricingAppliedLineItemProductDiscount
     */
    couponSetId?: number | null;
}

/**
 * Check if a given object implements the PricingAppliedLineItemProductDiscount interface.
 */
export function instanceOfPricingAppliedLineItemProductDiscount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PricingAppliedLineItemProductDiscountFromJSON(json: any): PricingAppliedLineItemProductDiscount {
    return PricingAppliedLineItemProductDiscountFromJSONTyped(json, false);
}

export function PricingAppliedLineItemProductDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingAppliedLineItemProductDiscount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appliesToSalePrice': !exists(json, 'appliesToSalePrice') ? undefined : json['appliesToSalePrice'],
        'impact': !exists(json, 'impact') ? undefined : json['impact'],
        'discount': !exists(json, 'discount') ? undefined : PricingDiscountFromJSON(json['discount']),
        'couponCode': !exists(json, 'couponCode') ? undefined : json['couponCode'],
        'couponSetId': !exists(json, 'couponSetId') ? undefined : json['couponSetId'],
    };
}

export function PricingAppliedLineItemProductDiscountToJSON(value?: PricingAppliedLineItemProductDiscount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appliesToSalePrice': value.appliesToSalePrice,
        'impact': value.impact,
        'discount': PricingDiscountToJSON(value.discount),
        'couponCode': value.couponCode,
        'couponSetId': value.couponSetId,
    };
}

