/* tslint:disable */
/* eslint-disable */
/**
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WishlistItem } from './WishlistItem';
import {
    WishlistItemFromJSON,
    WishlistItemFromJSONTyped,
    WishlistItemToJSON,
} from './WishlistItem';

/**
 * Paged collection of wishlists.
 * @export
 * @interface WishlistItemCollection
 */
export interface WishlistItemCollection {
    /**
     * 
     * @type {number}
     * @memberof WishlistItemCollection
     */
    startIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof WishlistItemCollection
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof WishlistItemCollection
     */
    pageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof WishlistItemCollection
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<WishlistItem>}
     * @memberof WishlistItemCollection
     */
    items?: Array<WishlistItem> | null;
}

/**
 * Check if a given object implements the WishlistItemCollection interface.
 */
export function instanceOfWishlistItemCollection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WishlistItemCollectionFromJSON(json: any): WishlistItemCollection {
    return WishlistItemCollectionFromJSONTyped(json, false);
}

export function WishlistItemCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishlistItemCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startIndex': !exists(json, 'startIndex') ? undefined : json['startIndex'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageCount': !exists(json, 'pageCount') ? undefined : json['pageCount'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(WishlistItemFromJSON)),
    };
}

export function WishlistItemCollectionToJSON(value?: WishlistItemCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startIndex': value.startIndex,
        'pageSize': value.pageSize,
        'pageCount': value.pageCount,
        'totalCount': value.totalCount,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(WishlistItemToJSON)),
    };
}

