/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The inventory for a product at a specific Location
 * @export
 * @interface CatalogRuntimesProductCost
 */
export interface CatalogRuntimesProductCost {
    /**
     * 
     * @type {string}
     * @memberof CatalogRuntimesProductCost
     */
    productCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CatalogRuntimesProductCost
     */
    cost?: number;
}

/**
 * Check if a given object implements the CatalogRuntimesProductCost interface.
 */
export function instanceOfCatalogRuntimesProductCost(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CatalogRuntimesProductCostFromJSON(json: any): CatalogRuntimesProductCost {
    return CatalogRuntimesProductCostFromJSONTyped(json, false);
}

export function CatalogRuntimesProductCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogRuntimesProductCost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productCode': !exists(json, 'productCode') ? undefined : json['productCode'],
        'cost': !exists(json, 'cost') ? undefined : json['cost'],
    };
}

export function CatalogRuntimesProductCostToJSON(value?: CatalogRuntimesProductCost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productCode': value.productCode,
        'cost': value.cost,
    };
}

