/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImageGroupTag
 */
export interface ProductImageGroupTag {
    /**
     * 
     * @type {string}
     * @memberof ProductImageGroupTag
     */
    attributeFqn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductImageGroupTag
     */
    value?: string | null;
}

/**
 * Check if a given object implements the ProductImageGroupTag interface.
 */
export function instanceOfProductImageGroupTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductImageGroupTagFromJSON(json: any): ProductImageGroupTag {
    return ProductImageGroupTagFromJSONTyped(json, false);
}

export function ProductImageGroupTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImageGroupTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeFqn': !exists(json, 'attributeFqn') ? undefined : json['attributeFqn'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ProductImageGroupTagToJSON(value?: ProductImageGroupTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeFqn': value.attributeFqn,
        'value': value.value,
    };
}

