/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';
import type { Manifest } from './Manifest';
import {
    ManifestFromJSON,
    ManifestFromJSONTyped,
    ManifestToJSON,
} from './Manifest';

/**
 * 
 * @export
 * @interface CollectionModelOfManifest
 */
export interface CollectionModelOfManifest {
    /**
     * 
     * @type {{ [key: string]: Array<Manifest>; }}
     * @memberof CollectionModelOfManifest
     */
    embedded?: { [key: string]: Array<Manifest>; };
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelOfManifest
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelOfManifest interface.
 */
export function instanceOfCollectionModelOfManifest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CollectionModelOfManifestFromJSON(json: any): CollectionModelOfManifest {
    return CollectionModelOfManifestFromJSONTyped(json, false);
}

export function CollectionModelOfManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelOfManifest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedded': !exists(json, '_embedded') ? undefined : json['_embedded'],
        'links': !exists(json, '_links') ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelOfManifestToJSON(value?: CollectionModelOfManifest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_embedded': value.embedded,
        '_links': value.links === undefined ? undefined : (mapValues(value.links, LinkToJSON)),
    };
}

