/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuditInfo0 } from './AuditInfo0';
import {
    AuditInfo0FromJSON,
    AuditInfo0FromJSONTyped,
    AuditInfo0ToJSON,
} from './AuditInfo0';
import type { FulfillmentAppeasementReason } from './FulfillmentAppeasementReason';
import {
    FulfillmentAppeasementReasonFromJSON,
    FulfillmentAppeasementReasonFromJSONTyped,
    FulfillmentAppeasementReasonToJSON,
} from './FulfillmentAppeasementReason';
import type { FulfillmentFulfillmentField } from './FulfillmentFulfillmentField';
import {
    FulfillmentFulfillmentFieldFromJSON,
    FulfillmentFulfillmentFieldFromJSONTyped,
    FulfillmentFulfillmentFieldToJSON,
} from './FulfillmentFulfillmentField';
import type { FulfillmentGiftCard } from './FulfillmentGiftCard';
import {
    FulfillmentGiftCardFromJSON,
    FulfillmentGiftCardFromJSONTyped,
    FulfillmentGiftCardToJSON,
} from './FulfillmentGiftCard';
import type { FulfillmentInventoryTag } from './FulfillmentInventoryTag';
import {
    FulfillmentInventoryTagFromJSON,
    FulfillmentInventoryTagFromJSONTyped,
    FulfillmentInventoryTagToJSON,
} from './FulfillmentInventoryTag';
import type { FulfillmentProductOption } from './FulfillmentProductOption';
import {
    FulfillmentProductOptionFromJSON,
    FulfillmentProductOptionFromJSONTyped,
    FulfillmentProductOptionToJSON,
} from './FulfillmentProductOption';

/**
 * 
 * @export
 * @interface FulfillmentItem
 */
export interface FulfillmentItem {
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    actualPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    allocatedQuantity?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    allowsBackOrder?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    allowsFutureAllocate?: boolean;
    /**
     * 
     * @type {FulfillmentAppeasementReason}
     * @memberof FulfillmentItem
     */
    appeasementReason?: FulfillmentAppeasementReason;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof FulfillmentItem
     */
    attributes?: { [key: string]: object; };
    /**
     * 
     * @type {AuditInfo0}
     * @memberof FulfillmentItem
     */
    auditInfo?: AuditInfo0;
    /**
     * 
     * @type {Date}
     * @memberof FulfillmentItem
     */
    backorderReleaseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    cartItemId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FulfillmentItem
     */
    childItemIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    creditCurrencyCode?: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    creditValue?: number;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof FulfillmentItem
     */
    data?: { [key: string]: object; };
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    duty?: number;
    /**
     * 
     * @type {Date}
     * @memberof FulfillmentItem
     */
    expectedDeliveryDate?: Date;
    /**
     * 
     * @type {Array<FulfillmentFulfillmentField>}
     * @memberof FulfillmentItem
     */
    fulfillmentFields?: Array<FulfillmentFulfillmentField>;
    /**
     * 
     * @type {Array<FulfillmentGiftCard>}
     * @memberof FulfillmentItem
     */
    giftCards?: Array<FulfillmentGiftCard>;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    goodsType?: FulfillmentItemGoodsTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    handling: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    handlingDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    handlingTax: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    imageUrl?: string;
    /**
     * 
     * @type {Array<FulfillmentInventoryTag>}
     * @memberof FulfillmentItem
     */
    inventoryTags?: Array<FulfillmentInventoryTag>;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    isAssemblyRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    isPackagedStandAlone?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    isReservedInventory?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    isTaxable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    itemDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    itemTax: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    lineId: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    lineItemAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    lineItemCost?: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    locatorName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FulfillmentItem
     */
    manageStock?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    optionAttributeFQN?: string;
    /**
     * 
     * @type {Array<FulfillmentProductOption>}
     * @memberof FulfillmentItem
     */
    options?: Array<FulfillmentProductOption>;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    originalOrderItemId?: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    overridePrice?: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    parentItemId?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    partNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    productCode?: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    readyForPickupQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    shipping: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    shippingDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    shippingTax: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    sku?: string;
    /**
     * 
     * @type {object}
     * @memberof FulfillmentItem
     */
    taxData?: object;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    taxableHandling?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    taxableLineItemCost?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    taxableShipping?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    transferQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    trueTransferQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    unitPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    upc?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    variationProductCode?: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    weightUnit?: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedDutyAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedHandlingAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedHandlingTaxAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedLineItemTaxAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedShipmentAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedShippingAdjustment?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    weightedShippingTaxAdjustment?: number;
}


/**
 * @export
 */
export const FulfillmentItemGoodsTypeEnum = {
    Digital: 'Digital',
    DigitalCredit: 'DigitalCredit',
    DigitalGiftCard: 'DigitalGiftCard',
    Physical: 'Physical',
    Service: 'Service'
} as const;
export type FulfillmentItemGoodsTypeEnum = typeof FulfillmentItemGoodsTypeEnum[keyof typeof FulfillmentItemGoodsTypeEnum];


/**
 * Check if a given object implements the FulfillmentItem interface.
 */
export function instanceOfFulfillmentItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "handling" in value;
    isInstance = isInstance && "handlingTax" in value;
    isInstance = isInstance && "itemTax" in value;
    isInstance = isInstance && "lineId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "shipping" in value;
    isInstance = isInstance && "shippingTax" in value;

    return isInstance;
}

export function FulfillmentItemFromJSON(json: any): FulfillmentItem {
    return FulfillmentItemFromJSONTyped(json, false);
}

export function FulfillmentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actualPrice': !exists(json, 'actualPrice') ? undefined : json['actualPrice'],
        'allocatedQuantity': !exists(json, 'allocatedQuantity') ? undefined : json['allocatedQuantity'],
        'allowsBackOrder': !exists(json, 'allowsBackOrder') ? undefined : json['allowsBackOrder'],
        'allowsFutureAllocate': !exists(json, 'allowsFutureAllocate') ? undefined : json['allowsFutureAllocate'],
        'appeasementReason': !exists(json, 'appeasementReason') ? undefined : FulfillmentAppeasementReasonFromJSON(json['appeasementReason']),
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'auditInfo': !exists(json, 'auditInfo') ? undefined : AuditInfo0FromJSON(json['auditInfo']),
        'backorderReleaseDate': !exists(json, 'backorderReleaseDate') ? undefined : (new Date(json['backorderReleaseDate'])),
        'cartItemId': !exists(json, 'cartItemId') ? undefined : json['cartItemId'],
        'childItemIds': !exists(json, 'childItemIds') ? undefined : json['childItemIds'],
        'creditCurrencyCode': !exists(json, 'creditCurrencyCode') ? undefined : json['creditCurrencyCode'],
        'creditValue': !exists(json, 'creditValue') ? undefined : json['creditValue'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'duty': !exists(json, 'duty') ? undefined : json['duty'],
        'expectedDeliveryDate': !exists(json, 'expectedDeliveryDate') ? undefined : (new Date(json['expectedDeliveryDate'])),
        'fulfillmentFields': !exists(json, 'fulfillmentFields') ? undefined : ((json['fulfillmentFields'] as Array<any>).map(FulfillmentFulfillmentFieldFromJSON)),
        'giftCards': !exists(json, 'giftCards') ? undefined : ((json['giftCards'] as Array<any>).map(FulfillmentGiftCardFromJSON)),
        'goodsType': !exists(json, 'goodsType') ? undefined : json['goodsType'],
        'handling': json['handling'],
        'handlingDiscount': !exists(json, 'handlingDiscount') ? undefined : json['handlingDiscount'],
        'handlingTax': json['handlingTax'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'inventoryTags': !exists(json, 'inventoryTags') ? undefined : ((json['inventoryTags'] as Array<any>).map(FulfillmentInventoryTagFromJSON)),
        'isAssemblyRequired': !exists(json, 'isAssemblyRequired') ? undefined : json['isAssemblyRequired'],
        'isPackagedStandAlone': !exists(json, 'isPackagedStandAlone') ? undefined : json['isPackagedStandAlone'],
        'isReservedInventory': !exists(json, 'isReservedInventory') ? undefined : json['isReservedInventory'],
        'isTaxable': !exists(json, 'isTaxable') ? undefined : json['isTaxable'],
        'itemDiscount': !exists(json, 'itemDiscount') ? undefined : json['itemDiscount'],
        'itemTax': json['itemTax'],
        'lineId': json['lineId'],
        'lineItemAdjustment': !exists(json, 'lineItemAdjustment') ? undefined : json['lineItemAdjustment'],
        'lineItemCost': !exists(json, 'lineItemCost') ? undefined : json['lineItemCost'],
        'locatorName': !exists(json, 'locatorName') ? undefined : json['locatorName'],
        'manageStock': !exists(json, 'manageStock') ? undefined : json['manageStock'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'optionAttributeFQN': !exists(json, 'optionAttributeFQN') ? undefined : json['optionAttributeFQN'],
        'options': !exists(json, 'options') ? undefined : ((json['options'] as Array<any>).map(FulfillmentProductOptionFromJSON)),
        'originalOrderItemId': !exists(json, 'originalOrderItemId') ? undefined : json['originalOrderItemId'],
        'overridePrice': !exists(json, 'overridePrice') ? undefined : json['overridePrice'],
        'parentItemId': !exists(json, 'parentItemId') ? undefined : json['parentItemId'],
        'partNumber': !exists(json, 'partNumber') ? undefined : json['partNumber'],
        'productCode': !exists(json, 'productCode') ? undefined : json['productCode'],
        'quantity': json['quantity'],
        'readyForPickupQuantity': !exists(json, 'readyForPickupQuantity') ? undefined : json['readyForPickupQuantity'],
        'shipping': json['shipping'],
        'shippingDiscount': !exists(json, 'shippingDiscount') ? undefined : json['shippingDiscount'],
        'shippingTax': json['shippingTax'],
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'taxData': !exists(json, 'taxData') ? undefined : json['taxData'],
        'taxableHandling': !exists(json, 'taxableHandling') ? undefined : json['taxableHandling'],
        'taxableLineItemCost': !exists(json, 'taxableLineItemCost') ? undefined : json['taxableLineItemCost'],
        'taxableShipping': !exists(json, 'taxableShipping') ? undefined : json['taxableShipping'],
        'transferQuantity': !exists(json, 'transferQuantity') ? undefined : json['transferQuantity'],
        'trueTransferQuantity': !exists(json, 'trueTransferQuantity') ? undefined : json['trueTransferQuantity'],
        'unitPrice': !exists(json, 'unitPrice') ? undefined : json['unitPrice'],
        'upc': !exists(json, 'upc') ? undefined : json['upc'],
        'variationProductCode': !exists(json, 'variationProductCode') ? undefined : json['variationProductCode'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'weightUnit': !exists(json, 'weightUnit') ? undefined : json['weightUnit'],
        'weightedDutyAdjustment': !exists(json, 'weightedDutyAdjustment') ? undefined : json['weightedDutyAdjustment'],
        'weightedHandlingAdjustment': !exists(json, 'weightedHandlingAdjustment') ? undefined : json['weightedHandlingAdjustment'],
        'weightedHandlingTaxAdjustment': !exists(json, 'weightedHandlingTaxAdjustment') ? undefined : json['weightedHandlingTaxAdjustment'],
        'weightedLineItemTaxAdjustment': !exists(json, 'weightedLineItemTaxAdjustment') ? undefined : json['weightedLineItemTaxAdjustment'],
        'weightedShipmentAdjustment': !exists(json, 'weightedShipmentAdjustment') ? undefined : json['weightedShipmentAdjustment'],
        'weightedShippingAdjustment': !exists(json, 'weightedShippingAdjustment') ? undefined : json['weightedShippingAdjustment'],
        'weightedShippingTaxAdjustment': !exists(json, 'weightedShippingTaxAdjustment') ? undefined : json['weightedShippingTaxAdjustment'],
    };
}

export function FulfillmentItemToJSON(value?: FulfillmentItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actualPrice': value.actualPrice,
        'allocatedQuantity': value.allocatedQuantity,
        'allowsBackOrder': value.allowsBackOrder,
        'allowsFutureAllocate': value.allowsFutureAllocate,
        'appeasementReason': FulfillmentAppeasementReasonToJSON(value.appeasementReason),
        'attributes': value.attributes,
        'auditInfo': AuditInfo0ToJSON(value.auditInfo),
        'backorderReleaseDate': value.backorderReleaseDate === undefined ? undefined : (value.backorderReleaseDate.toISOString()),
        'cartItemId': value.cartItemId,
        'childItemIds': value.childItemIds,
        'creditCurrencyCode': value.creditCurrencyCode,
        'creditValue': value.creditValue,
        'data': value.data,
        'duty': value.duty,
        'expectedDeliveryDate': value.expectedDeliveryDate === undefined ? undefined : (value.expectedDeliveryDate.toISOString()),
        'fulfillmentFields': value.fulfillmentFields === undefined ? undefined : ((value.fulfillmentFields as Array<any>).map(FulfillmentFulfillmentFieldToJSON)),
        'giftCards': value.giftCards === undefined ? undefined : ((value.giftCards as Array<any>).map(FulfillmentGiftCardToJSON)),
        'goodsType': value.goodsType,
        'handling': value.handling,
        'handlingDiscount': value.handlingDiscount,
        'handlingTax': value.handlingTax,
        'imageUrl': value.imageUrl,
        'inventoryTags': value.inventoryTags === undefined ? undefined : ((value.inventoryTags as Array<any>).map(FulfillmentInventoryTagToJSON)),
        'isAssemblyRequired': value.isAssemblyRequired,
        'isPackagedStandAlone': value.isPackagedStandAlone,
        'isReservedInventory': value.isReservedInventory,
        'isTaxable': value.isTaxable,
        'itemDiscount': value.itemDiscount,
        'itemTax': value.itemTax,
        'lineId': value.lineId,
        'lineItemAdjustment': value.lineItemAdjustment,
        'lineItemCost': value.lineItemCost,
        'locatorName': value.locatorName,
        'manageStock': value.manageStock,
        'name': value.name,
        'optionAttributeFQN': value.optionAttributeFQN,
        'options': value.options === undefined ? undefined : ((value.options as Array<any>).map(FulfillmentProductOptionToJSON)),
        'originalOrderItemId': value.originalOrderItemId,
        'overridePrice': value.overridePrice,
        'parentItemId': value.parentItemId,
        'partNumber': value.partNumber,
        'productCode': value.productCode,
        'quantity': value.quantity,
        'readyForPickupQuantity': value.readyForPickupQuantity,
        'shipping': value.shipping,
        'shippingDiscount': value.shippingDiscount,
        'shippingTax': value.shippingTax,
        'sku': value.sku,
        'taxData': value.taxData,
        'taxableHandling': value.taxableHandling,
        'taxableLineItemCost': value.taxableLineItemCost,
        'taxableShipping': value.taxableShipping,
        'transferQuantity': value.transferQuantity,
        'trueTransferQuantity': value.trueTransferQuantity,
        'unitPrice': value.unitPrice,
        'upc': value.upc,
        'variationProductCode': value.variationProductCode,
        'weight': value.weight,
        'weightUnit': value.weightUnit,
        'weightedDutyAdjustment': value.weightedDutyAdjustment,
        'weightedHandlingAdjustment': value.weightedHandlingAdjustment,
        'weightedHandlingTaxAdjustment': value.weightedHandlingTaxAdjustment,
        'weightedLineItemTaxAdjustment': value.weightedLineItemTaxAdjustment,
        'weightedShipmentAdjustment': value.weightedShipmentAdjustment,
        'weightedShippingAdjustment': value.weightedShippingAdjustment,
        'weightedShippingTaxAdjustment': value.weightedShippingTaxAdjustment,
    };
}

