/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Shipping Admin Service
 * OpenAPI Spec for Kibo Shipping Admin Service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../../client-runtime';
import { basePathTemplate } from '../api-path';
import type {
  CarrierDefinition,
} from '../models';


export namespace carrierDefinitionApiParams { 
    export interface GetCarrierDefinitionRequest {
        carrierId: string;
        responseFields?: string;
    }
    export interface GetCarrierDefinitionsRequest {
        responseFields?: string;
    }
}
/**
* CarrierDefinitionApiService - interface
* 
* @export
* @interface CarrierDefinitionApi
*/
export interface CarrierDefinitionApiService {
    /**
    * Retrieves the carrier definition for the specified carrier
    * @summary Get Carrier Definition
    * @param {string} carrierId The carrier ID.
    * @param {string} [responseFields] limits which fields are returned in the response body
    * @param {*} [options] Override http request option.
    * @throws {RequiredError}
    * @memberof CarrierDefinitionApiInterface
    */
    getCarrierDefinitionRaw(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarrierDefinition>>;

    /**
    * Retrieves the carrier definition for the specified carrier
    * Get Carrier Definition
    */
    getCarrierDefinition(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarrierDefinition>;

    /**
    * Retrieves all shipping carrier definitions for the specified tenant
    * @summary Get Carrier Definitions
    * @param {string} [responseFields] limits which fields are returned in the response body
    * @param {*} [options] Override http request option.
    * @throws {RequiredError}
    * @memberof CarrierDefinitionApiInterface
    */
    getCarrierDefinitionsRaw(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CarrierDefinition>>>;

    /**
    * Retrieves all shipping carrier definitions for the specified tenant
    * Get Carrier Definitions
    */
    getCarrierDefinitions(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CarrierDefinition>>;

}


/**
 * 
 */
export class CarrierDefinitionApi extends runtime.BaseAPI implements CarrierDefinitionApiService {
    constructor(configuration?) {
        super(configuration)
        this.basePathTemplate = basePathTemplate
    }
    /**
     * Retrieves the carrier definition for the specified carrier
     * Get Carrier Definition
     */


    async getCarrierDefinitionRaw(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarrierDefinition>> {
        if (requestParameters.carrierId === null || requestParameters.carrierId === undefined) {
            throw new runtime.RequiredError('carrierId','Required parameter requestParameters.carrierId was null or undefined when calling getCarrierDefinition.');
        }

        const queryParameters: any = {};

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};



        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/commerce/shipping/admin/carriers/definitions/{carrierId}`.replace(`{${"carrierId"}}`, encodeURIComponent(String(requestParameters.carrierId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the carrier definition for the specified carrier
     * Get Carrier Definition
     */
    async getCarrierDefinition(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarrierDefinition> {
        const response = await this.getCarrierDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all shipping carrier definitions for the specified tenant
     * Get Carrier Definitions
     */


    async getCarrierDefinitionsRaw(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CarrierDefinition>>> {
        const queryParameters: any = {};

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};



        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/commerce/shipping/admin/carriers/definitions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves all shipping carrier definitions for the specified tenant
     * Get Carrier Definitions
     */
    async getCarrierDefinitions(requestParameters: carrierDefinitionApiParams.GetCarrierDefinitionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CarrierDefinition>> {
        const response = await this.getCarrierDefinitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
