/* tslint:disable */
/* eslint-disable */
/**
 * Kibo MZDB Service
 * OpenAPI Spec for Kibo MZDB Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../../client-runtime';
import { basePathTemplate } from '../api-path';
import type {
  EntityContainer,
  EntityContainerCollection,
} from '../models';

export interface EntityContainersApiGetEntityContainerRequest {
    entityListFullName: string;
    id: string;
    responseFields?: string;
}

export interface EntityContainersApiGetEntityContainersRequest {
    entityListFullName: string;
    pageSize?: number;
    startIndex?: number;
    filter?: string;
    sortBy?: string;
    responseFields?: string;
}

export interface EntityContainersApiGetViewEntityContainerRequest {
    entityListFullName: string;
    viewName: string;
    entityId: string;
    responseFields?: string;
}

export interface EntityContainersApiGetViewEntityContainersRequest {
    entityListFullName: string;
    viewName: string;
    pageSize?: number;
    startIndex?: number;
    filter?: string;
    responseFields?: string;
}

/**
 * EntityContainersApi - interface
 * 
 * @export
 * @interface EntityContainersApiInterface
 */
export interface EntityContainersApiInterface {
    /**
     * Get a specific Entity Container from an  EntityList instance
     * @summary Get Entity Container
     * @param {string} entityListFullName The full name of the EntityList including namespace in name@nameSpace format
     * @param {string} id The unique id of the Entity
     * @param {string} [responseFields] limits which fields are returned in the response body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityContainersApiInterface
     */
    getEntityContainerRaw(requestParameters: EntityContainersApiGetEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainer>>;

    /**
     * Get a specific Entity Container from an  EntityList instance
     * Get Entity Container
     */
    getEntityContainer(requestParameters: EntityContainersApiGetEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainer>;

    /**
     * Get a filtered collection of Entity Containers from an Entity List instance
     * @summary Get Entity Containers
     * @param {string} entityListFullName The full name of the EntityList including namespace in name@nameSpace format
     * @param {number} [pageSize] 
     * @param {number} [startIndex] 
     * @param {string} [filter] 
     * @param {string} [sortBy] 
     * @param {string} [responseFields] limits which fields are returned in the response body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityContainersApiInterface
     */
    getEntityContainersRaw(requestParameters: EntityContainersApiGetEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainerCollection>>;

    /**
     * Get a filtered collection of Entity Containers from an Entity List instance
     * Get Entity Containers
     */
    getEntityContainers(requestParameters: EntityContainersApiGetEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainerCollection>;

    /**
     * Get an Entity Container for a specific Entity in a ListView on an EntityList
     * @summary Get  Entity View Container
     * @param {string} entityListFullName The full name of the EntityList including namespace in name@nameSpace format
     * @param {string} viewName The name of the ListView
     * @param {string} entityId The unique Entity id
     * @param {string} [responseFields] limits which fields are returned in the response body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityContainersApiInterface
     */
    getViewEntityContainerRaw(requestParameters: EntityContainersApiGetViewEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainer>>;

    /**
     * Get an Entity Container for a specific Entity in a ListView on an EntityList
     * Get  Entity View Container
     */
    getViewEntityContainer(requestParameters: EntityContainersApiGetViewEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainer>;

    /**
     * Get a filtered collection of Entity Containers for a ListView on an EntityList
     * @summary Get Entity View Containers
     * @param {string} entityListFullName The full name of the EntityList including namespace in name@nameSpace format
     * @param {string} viewName The name of the ListView
     * @param {number} [pageSize] 
     * @param {number} [startIndex] 
     * @param {string} [filter] 
     * @param {string} [responseFields] limits which fields are returned in the response body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityContainersApiInterface
     */
    getViewEntityContainersRaw(requestParameters: EntityContainersApiGetViewEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainerCollection>>;

    /**
     * Get a filtered collection of Entity Containers for a ListView on an EntityList
     * Get Entity View Containers
     */
    getViewEntityContainers(requestParameters: EntityContainersApiGetViewEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainerCollection>;

}

/**
 * 
 */
export class EntityContainersApi extends runtime.BaseAPI implements EntityContainersApiInterface {
    constructor(configuration?) {
        super(configuration)
        this.basePathTemplate = basePathTemplate
    }
    /**
     * Get a specific Entity Container from an  EntityList instance
     * Get Entity Container
     */


    async getEntityContainerRaw(requestParameters: EntityContainersApiGetEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainer>> {
        if (requestParameters.entityListFullName === null || requestParameters.entityListFullName === undefined) {
            throw new runtime.RequiredError('entityListFullName','Required parameter requestParameters.entityListFullName was null or undefined when calling getEntityContainer.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getEntityContainer.');
        }

        const queryParameters: any = {};

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};





        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/platform/entitylists/{entityListFullName}/entityContainers/{id}`.replace(`{${"entityListFullName"}}`, encodeURIComponent(String(requestParameters.entityListFullName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a specific Entity Container from an  EntityList instance
     * Get Entity Container
     */
    async getEntityContainer(requestParameters: EntityContainersApiGetEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainer> {
        const response = await this.getEntityContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a filtered collection of Entity Containers from an Entity List instance
     * Get Entity Containers
     */


    async getEntityContainersRaw(requestParameters: EntityContainersApiGetEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainerCollection>> {
        if (requestParameters.entityListFullName === null || requestParameters.entityListFullName === undefined) {
            throw new runtime.RequiredError('entityListFullName','Required parameter requestParameters.entityListFullName was null or undefined when calling getEntityContainers.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.startIndex !== undefined) {
            queryParameters['startIndex'] = requestParameters.startIndex;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};





        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/platform/entitylists/{entityListFullName}/entityContainers`.replace(`{${"entityListFullName"}}`, encodeURIComponent(String(requestParameters.entityListFullName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a filtered collection of Entity Containers from an Entity List instance
     * Get Entity Containers
     */
    async getEntityContainers(requestParameters: EntityContainersApiGetEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainerCollection> {
        const response = await this.getEntityContainersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an Entity Container for a specific Entity in a ListView on an EntityList
     * Get  Entity View Container
     */


    async getViewEntityContainerRaw(requestParameters: EntityContainersApiGetViewEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainer>> {
        if (requestParameters.entityListFullName === null || requestParameters.entityListFullName === undefined) {
            throw new runtime.RequiredError('entityListFullName','Required parameter requestParameters.entityListFullName was null or undefined when calling getViewEntityContainer.');
        }

        if (requestParameters.viewName === null || requestParameters.viewName === undefined) {
            throw new runtime.RequiredError('viewName','Required parameter requestParameters.viewName was null or undefined when calling getViewEntityContainer.');
        }

        if (requestParameters.entityId === null || requestParameters.entityId === undefined) {
            throw new runtime.RequiredError('entityId','Required parameter requestParameters.entityId was null or undefined when calling getViewEntityContainer.');
        }

        const queryParameters: any = {};

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};





        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers/{entityId}`.replace(`{${"entityListFullName"}}`, encodeURIComponent(String(requestParameters.entityListFullName))).replace(`{${"viewName"}}`, encodeURIComponent(String(requestParameters.viewName))).replace(`{${"entityId"}}`, encodeURIComponent(String(requestParameters.entityId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get an Entity Container for a specific Entity in a ListView on an EntityList
     * Get  Entity View Container
     */
    async getViewEntityContainer(requestParameters: EntityContainersApiGetViewEntityContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainer> {
        const response = await this.getViewEntityContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a filtered collection of Entity Containers for a ListView on an EntityList
     * Get Entity View Containers
     */


    async getViewEntityContainersRaw(requestParameters: EntityContainersApiGetViewEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityContainerCollection>> {
        if (requestParameters.entityListFullName === null || requestParameters.entityListFullName === undefined) {
            throw new runtime.RequiredError('entityListFullName','Required parameter requestParameters.entityListFullName was null or undefined when calling getViewEntityContainers.');
        }

        if (requestParameters.viewName === null || requestParameters.viewName === undefined) {
            throw new runtime.RequiredError('viewName','Required parameter requestParameters.viewName was null or undefined when calling getViewEntityContainers.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.startIndex !== undefined) {
            queryParameters['startIndex'] = requestParameters.startIndex;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.responseFields !== undefined) {
            queryParameters['responseFields'] = requestParameters.responseFields;
        }

        const headerParameters: runtime.HTTPHeaders = {};





        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers`.replace(`{${"entityListFullName"}}`, encodeURIComponent(String(requestParameters.entityListFullName))).replace(`{${"viewName"}}`, encodeURIComponent(String(requestParameters.viewName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a filtered collection of Entity Containers for a ListView on an EntityList
     * Get Entity View Containers
     */
    async getViewEntityContainers(requestParameters: EntityContainersApiGetViewEntityContainersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityContainerCollection> {
        const response = await this.getViewEntityContainersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
