/* tslint:disable */
/* eslint-disable */
/**
 * Order Routing
 * <div id=\"overview_ORDERROUTING\">             <h2>ORDER ROUTING</h2>             <p>Although the <a href=\"/developer-guides/order-routing\">Order Routing                     interface</a> is the best place to configure order routing rules, some                 aspects of routing can be managed through REST API calls when convenient.</p>             <p>Use the <strong>Data List</strong> resource to define the cases for which routing filters are applied.</p>             <p>Use the <strong>Routing Filter</strong> resource to configure sets of rules that filter out fulfillers that do not match given order criteria.</p>             <p>Use the <strong>Routing Group</strong> resource to manage and sort location groups specifically in context of routing                 preferences.</p>             <p>Use the general <strong>Routing</strong> resource to test your order routing configurations, such as by retrieving a list of eligible fulfillers for a certain order based on set                 routing rules or obtain a log of order routing decisions.</p>         </div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../../client-runtime';
import { basePathTemplate } from '../api-path';
import type {
  APIErrorResponse,
  StrategyExportDto,
  StrategyImportDto,
} from '../models';


export namespace orderRoutingStrategyExportApiParams { 
    export interface ExportStrategyRequest {
        xVolTenant: number;
        xVolSite: number;
        strategyId: string;
    }
    export interface ImportStrategyRequest {
        xVolTenant: number;
        xVolSite: number;
        strategyImportDto: StrategyImportDto;
    }
}
/**
* OrderRoutingStrategyExportApiService - interface
* 
* @export
* @interface OrderRoutingStrategyExportApi
*/
export interface OrderRoutingStrategyExportApiService {
    /**
    * Export Strategy
    * @summary Export Strategy
    * @param {number} xVolTenant 
    * @param {number} xVolSite 
    * @param {string} strategyId 
    * @param {*} [options] Override http request option.
    * @throws {RequiredError}
    * @memberof OrderRoutingStrategyExportApiInterface
    */
    exportStrategyRaw(requestParameters: orderRoutingStrategyExportApiParams.ExportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrategyExportDto>>;

    /**
    * Export Strategy
    * Export Strategy
    */
    exportStrategy(requestParameters: orderRoutingStrategyExportApiParams.ExportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrategyExportDto>;

    /**
    * Import Strategy
    * @summary Import Strategy
    * @param {number} xVolTenant 
    * @param {number} xVolSite 
    * @param {StrategyImportDto} strategyImportDto 
    * @param {*} [options] Override http request option.
    * @throws {RequiredError}
    * @memberof OrderRoutingStrategyExportApiInterface
    */
    importStrategyRaw(requestParameters: orderRoutingStrategyExportApiParams.ImportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
    * Import Strategy
    * Import Strategy
    */
    importStrategy(requestParameters: orderRoutingStrategyExportApiParams.ImportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}


/**
 * 
 */
export class OrderRoutingStrategyExportApi extends runtime.BaseAPI implements OrderRoutingStrategyExportApiService {
    constructor(configuration?) {
        super(configuration)
        this.basePathTemplate = basePathTemplate
    }
    /**
     * Export Strategy
     * Export Strategy
     */


    async exportStrategyRaw(requestParameters: orderRoutingStrategyExportApiParams.ExportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StrategyExportDto>> {
        if (requestParameters.xVolTenant === null || requestParameters.xVolTenant === undefined) {
            throw new runtime.RequiredError('xVolTenant','Required parameter requestParameters.xVolTenant was null or undefined when calling exportStrategy.');
        }

        if (requestParameters.xVolSite === null || requestParameters.xVolSite === undefined) {
            throw new runtime.RequiredError('xVolSite','Required parameter requestParameters.xVolSite was null or undefined when calling exportStrategy.');
        }

        if (requestParameters.strategyId === null || requestParameters.strategyId === undefined) {
            throw new runtime.RequiredError('strategyId','Required parameter requestParameters.strategyId was null or undefined when calling exportStrategy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xVolTenant !== undefined && requestParameters.xVolTenant !== null) {
            headerParameters['x-vol-tenant'] = String(requestParameters.xVolTenant);
        }

        if (requestParameters.xVolSite !== undefined && requestParameters.xVolSite !== null) {
            headerParameters['x-vol-site'] = String(requestParameters.xVolSite);
        }



        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/commerce/orders/orderrouting/api/v1/strategies/{strategyId}/export`.replace(`{${"strategyId"}}`, encodeURIComponent(String(requestParameters.strategyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Export Strategy
     * Export Strategy
     */
    async exportStrategy(requestParameters: orderRoutingStrategyExportApiParams.ExportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StrategyExportDto> {
        const response = await this.exportStrategyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Strategy
     * Import Strategy
     */


    async importStrategyRaw(requestParameters: orderRoutingStrategyExportApiParams.ImportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.xVolTenant === null || requestParameters.xVolTenant === undefined) {
            throw new runtime.RequiredError('xVolTenant','Required parameter requestParameters.xVolTenant was null or undefined when calling importStrategy.');
        }

        if (requestParameters.xVolSite === null || requestParameters.xVolSite === undefined) {
            throw new runtime.RequiredError('xVolSite','Required parameter requestParameters.xVolSite was null or undefined when calling importStrategy.');
        }

        if (requestParameters.strategyImportDto === null || requestParameters.strategyImportDto === undefined) {
            throw new runtime.RequiredError('strategyImportDto','Required parameter requestParameters.strategyImportDto was null or undefined when calling importStrategy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xVolTenant !== undefined && requestParameters.xVolTenant !== null) {
            headerParameters['x-vol-tenant'] = String(requestParameters.xVolTenant);
        }

        if (requestParameters.xVolSite !== undefined && requestParameters.xVolSite !== null) {
            headerParameters['x-vol-site'] = String(requestParameters.xVolSite);
        }



        await this.addAuthorizationHeaders(headerParameters)
        
        const response = await this.request({
            path: `/commerce/orders/orderrouting/api/v1/strategies/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.strategyImportDto,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Import Strategy
     * Import Strategy
     */
    async importStrategy(requestParameters: orderRoutingStrategyExportApiParams.ImportStrategyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.importStrategyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
