/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Location Admin Service
 * <div id=\"overview_LOCATION_ADMIN\">             <h2>LOCATION ADMINISTRATION</h2>             <p>The Location and Location Groups APIs enable tenants to associate a physical address with product inventory,                 provide a store finder for in-store pickup, or both and manage these locations at individual and group levels. See the                 <a href=\"/pages/locations\">Location user guides</a>                 for information about the related feature in the Unified Commerce Admin.</p>             <p>The <strong>Location Admin</strong>                 resource                 allows information about the individual locations to be accessed and edited, including creating new                 locations.</p>             <p>Use the <strong>Location Group</strong> and <strong>Location Group Configuration</strong> resources to manage groups, or sets of similar fulfillment locations that are bundled together                 to improve efficiency of managing configurations based on catalogs, custom fulfillment flows,                 available carrier options, and so forth.</p>             <p>Use the <strong>Location Types</strong> resource to manage the types of locations your tenant maintains, such as                 warehouses,                 physical storefronts, and kiosks.</p>             <p>Use the <strong>Location Settings</strong> resource to to define the available usages; or the locations and                     location types that interact                     with a specified site.</p>         </div>
 *
 * The version of the OpenAPI document: v1_admin
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const basePathTemplate = 'https://{tenantPodHost}/api'
