/* tslint:disable */
/* eslint-disable */
/**
 * Kibo Customer Service
 * OpenAPI Spec for Kibo Customer Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Old password and new password.
 * @export
 * @interface CustomerPasswordInfo
 */
export interface CustomerPasswordInfo {
    /**
     * Old password.
     * @type {string}
     * @memberof CustomerPasswordInfo
     */
    oldPassword?: string | null;
    /**
     * New password.
     * @type {string}
     * @memberof CustomerPasswordInfo
     */
    newPassword?: string | null;
    /**
     * The External Password, typically used for imports in conjunction with a custom action
     * @type {string}
     * @memberof CustomerPasswordInfo
     */
    externalPassword?: string | null;
}

/**
 * Check if a given object implements the CustomerPasswordInfo interface.
 */
export function instanceOfCustomerPasswordInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomerPasswordInfoFromJSON(json: any): CustomerPasswordInfo {
    return CustomerPasswordInfoFromJSONTyped(json, false);
}

export function CustomerPasswordInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPasswordInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oldPassword': !exists(json, 'oldPassword') ? undefined : json['oldPassword'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
        'externalPassword': !exists(json, 'externalPassword') ? undefined : json['externalPassword'],
    };
}

export function CustomerPasswordInfoToJSON(value?: CustomerPasswordInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oldPassword': value.oldPassword,
        'newPassword': value.newPassword,
        'externalPassword': value.externalPassword,
    };
}

